### ISSUE TITLE
Add what happens when an alien wins/loses/ties a fight

### ISSUE THREAD

**Issue by guberti** [EastsidePreparatorySchool/Ephemera#19]
Before this can be coded we will need to decide what happens when an alien wins/loses/ties. Any insight  into what this might look like would be great.

**Comment by guberti** [comment]
Rules as documented on 3/22:

1. All participants invest some amount of energy. They all lose this.
2. The alien(s) with the highest amount of energy invested win.
3. All other aliens go down to tech = 2.
4. The alien that won goes to the highest tech level of all the defeated aliens.

**Comment by gunnarmein** [comment]
Comment on #4: The alien(s) that won will all go to the max tech level of defeated parties.

**Comment by gunnarmein** [comment]
Tech level should play a role in the outcome. Thoughts?
