### ISSUE TITLE
Implement Trading

### ISSUE THREAD

**Issue by guberti** [EastsidePreparatorySchool/Ephemera#26]
First ideas for trading:

Each alien has a sell price and a buy price for energy. If two aliens meet and agree to trade, the alien with higher tech is the seller and the alien with lower tech is the buyer (aliens can only trade one level of tech for energy at a time). The higher tech alien's sell price is compared with the lower tech alien's buy price. If the buy price is greater or equal to the sell price, the lower tech alien's tech is bumped up one level (the high tech alien's tech stays the same), and the sell price of energy is taken out of the buying alien's energy and placed into the selling alien's energy.

**Comment by abedi19** [comment]
That seems a bit difficult to manage as what if one alien wants to fight and the other alien wants to trade, what is  the result of that.

**Comment by guberti** [comment]
Unlike fighting, trading is a mutual action. If both parties don't agree to trade, the trade does not go through. If one party chooses to fight and the other chooses to trade, the trade does not occur but the fight does.

**Comment by abedi19** [comment]
In that case you may want to create a system of sort which has a flag of yes I am open for trading and also, I want to trade with this species and not this species and only if their tech level is greater than or less than mine, all of which is conveyed using user input. If you want I can help you write this part.

**Comment by guberti** [comment]
Prototype Implentation:

- Add an action "Trade or Defend"
- Params: Power for defense, sell price, buy price
- If anyone in a square wants to fight, all trading is off and the fight commences
- The fight powers of everyone who decided to trade are their powers for defense
- If no fight happens, defense costs a constant price (ctx.getDefenseCost()) (maybe 2?)

- Fight code must be altered to recognize defenders
- Trade code must first look for fighters and deny trading if anyone wants to fight

**Comment by guberti** [comment]
Prototype Trade System: See guide image [here](https://cloud.githubusercontent.com/assets/3069006/14723497/3f373382-07c6-11e6-8ae3-0c72476e7b35.JPG).

![trade system](https://cloud.githubusercontent.com/assets/3069006/14723497/3f373382-07c6-11e6-8ae3-0c72476e7b35.JPG)

**Comment by guberti** [comment]
See commit [268323a](https://github.com/EastsidePreparatorySchool/Ephemera/commit/268323a9cf7dc49b737f1e330e05925e851d06df), V1 code is now written.

**Comment by guberti** [comment]
Code appears to work. File an additional issue for bugs.
