### ISSUE TITLE
Fully Implement Residents

### ISSUE THREAD

**Issue by guberti** [EastsidePreparatorySchool/Ephemera#36]
Upon loading, residents are not added to any ArrayList (see SpaceGrid.java line 724). In addition, residents cannot trade or fight with other species.

**Comment by gunnarmein** [comment]
Haven't even started. I will implement them like stockaliens with cheat codes, in fact they might reside in the stockaliens package.

**Comment by gunnarmein** [comment]
There is now a working resident, and the game let's them do stuff.
